=== sergiogars/SEW/xml/etapa.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.uniovi.es" targetNamespace="http://www.uniovi.es" elementFormDefault="qualified">
  <xs:simpleType name="latitudGeografica">
    
    <xs:restriction base="xs:string">
      <xs:pattern value="[-+]?([0-9]|[1-8][0-9])º[ ]*([0-5]?[0-9])'[ ]*([0-5]?[0-9])(\.[0-9]+)?''|[-+]?90º[ ]*0{1,2}'[ ]*0{1,2}(\.0+)?''"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="longitudGeografica">
    <xs:annotation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="[-+]?([0-9]|[1-9][0-9]|1[0-7][0-9])º[ ]*([0-5]?[0-9])'[ ]*([0-5]?[0-9])(\.[0-9]+)?''|[-+]?180º[ ]*0{1,2}'[ ]*0{1,2}(\.0+)?''"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="urlReferencia">
    <xs:restriction base="xs:anyURI">
      <xs:pattern value="https?://.+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="textoNoVacio">
    <xs:restriction base="xs:token">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="duracionPositiva">
    <xs:annotation>
      
    </xs:annotation>
    <xs:restriction base="xs:duration">
      <xs:minExclusive value="PT0S"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="altitudTipo">
    <xs:restriction base="xs:decimal">
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="desnivelTipo">
    <xs:restriction base="xs:nonNegativeInteger">
      <xs:maxInclusive value="10000"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="velocidadTipo">
    <xs:restriction base="xs:decimal">
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="longitudEtapaTipo">
    <xs:restriction base="xs:decimal">
      <xs:minExclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="decimalNoNegativo">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="etapa">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element ref="numero"/>
        <xs:element ref="longitud_etapa"/>
        <xs:element ref="fecha"/>
        <xs:element ref="tiempo_ganador"/>
        <xs:element ref="velocidad_media"/>
        <xs:element ref="desnivel"/>
        <xs:element ref="salida"/>
        <xs:element ref="llegada"/>
        <xs:element ref="tipo"/>
        <xs:element ref="referencias"/>
        <xs:element ref="fotografias"/>
        <xs:element ref="videos"/>
        <xs:element ref="sonidos"/>
        <xs:element ref="hitos"/>
        <xs:element ref="puntos_anonimos"/>
        <xs:element ref="clasificacion_etapa"/>
        <xs:element ref="clasificacion_general"/>
        <xs:element ref="clasificacion_equipos"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombre" type="textoNoVacio"/>
  <xs:element name="numero" type="xs:positiveInteger"/>
  <xs:element name="longitud_etapa">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="longitudEtapaTipo">
          <xs:attribute name="unidades" type="xs:token" use="required" fixed="km"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="fecha" type="xs:date"/>
  <xs:element name="tiempo_ganador" type="duracionPositiva"/>
  <xs:element name="velocidad_media">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="velocidadTipo">
          <xs:attribute name="unidades" type="xs:token" use="required" fixed="km/h"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="desnivel">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="desnivelTipo">
          <xs:attribute name="unidades" type="xs:token" use="required" fixed="m"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="tipo">
    <xs:complexType>
      <xs:attribute name="valor" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="llana"/>
            <xs:enumeration value="montaña"/>
            <xs:enumeration value="media-montaña"/>
            <xs:enumeration value="contrarreloj-individual"/>
            <xs:enumeration value="contrarreloj-por-equipos"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="salida">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="lugar"/>
        <xs:element ref="coordenadas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="llegada">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="lugar"/>
        <xs:element ref="coordenadas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="lugar" type="textoNoVacio"/>
  <xs:element name="coordenadas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="longitud"/>
        <xs:element ref="latitud"/>
        <xs:element ref="altitud"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="longitud">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="longitudGeografica">
          <xs:attribute name="unidades" type="xs:token" use="required" fixed="grados"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="latitud">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="latitudGeografica">
          <xs:attribute name="unidades" type="xs:token" use="required" fixed="grados"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="altitud">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="altitudTipo">
          <xs:attribute name="unidades" type="xs:token" use="required" fixed="m"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="referencias">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="referencia" minOccurs="3" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="referencia" type="urlReferencia"/>
  <xs:element name="fotografias">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fotografia" minOccurs="1" maxOccurs="5"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fotografia">
    <xs:complexType>
      <xs:attribute name="archivo" type="xs:anyURI" use="required"/>
      <xs:attribute name="descripcion" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="videos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="video" minOccurs="1" maxOccurs="3"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="video">
    <xs:complexType>
      <xs:attribute name="archivo" type="xs:anyURI" use="required"/>
      <xs:attribute name="descripcion" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sonidos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="sonido" minOccurs="1" maxOccurs="3"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sonido">
    <xs:complexType>
      <xs:attribute name="archivo" type="xs:anyURI" use="required"/>
      <xs:attribute name="descripcion" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="distancia">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="decimalNoNegativo">
          <xs:attribute name="unidades" type="xs:token" use="required" fixed="km"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="hitos">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="puerto"/>
        <xs:element ref="sprint_intermedio"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="puerto">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element ref="coordenadas"/>
        <xs:element ref="distancia"/>
      </xs:sequence>
      <xs:attribute name="categoria" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="especial"/>
            <xs:enumeration value="primera"/>
            <xs:enumeration value="segunda"/>
            <xs:enumeration value="tercera"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute default="no" name="bonificado">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="si"/>
            <xs:enumeration value="no"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="sprint_intermedio">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="nombre"/>
        <xs:element ref="coordenadas"/>
        <xs:element ref="distancia"/>
      </xs:sequence>
      <xs:attribute default="no" name="bonificado">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="si"/>
            <xs:enumeration value="no"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="puntos_anonimos">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="punto"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="punto">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="coordenadas"/>
        <xs:element ref="distancia"/>
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="diferencia" type="duracionPositiva"/>
  <xs:element name="equipo" type="textoNoVacio"/>
  <xs:element name="clasificacion_etapa">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="clasificado"/>
        <xs:element ref="clasificado"/>
        <xs:element ref="clasificado"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="clasificacion_general">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="clasificado"/>
        <xs:element ref="clasificado"/>
        <xs:element ref="clasificado"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="clasificado">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element ref="equipo"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="diferencia"/>
      </xs:sequence>
      <xs:attribute name="posicion" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:positiveInteger">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="clasificacion_equipos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="equipo_clasificado"/>
        <xs:element ref="equipo_clasificado"/>
        <xs:element ref="equipo_clasificado"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="equipo_clasificado">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="diferencia"/>
      </xs:sequence>
      <xs:attribute name="posicion" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:positiveInteger">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sergiogars/SEW/xml/etapaEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<etapa xmlns="http://www.uniovi.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uniovi.es etapa.xsd">
  <nombre>Vall D’Alba a Aramón Valdelinares</nombre>
  <numero>7</numero>
  <longitud_etapa unidades="km">149.8</longitud_etapa>
  <fecha>2026-08-28</fecha>
  <tiempo_ganador>PT3H49M47S</tiempo_ganador>
  <velocidad_media unidades="km/h">39.11</velocidad_media>
  <desnivel unidades="m">3685</desnivel>

  <salida>
    <lugar>Salida lanzada en la CV-158, dirección Vilafamés</lugar>
            <coordenadas>
      <longitud unidades="grados">-0º 02' 24.00''</longitud>
      <latitud unidades="grados">40º 09' 32.40''</latitud>
      <altitud unidades="m">275</altitud>
    </coordenadas>
  </salida>

  <llegada>
    <lugar>Estación de esquí de Aramón Valdelinares</lugar>
            <coordenadas>
      <longitud unidades="grados">-0º 37' 58.01''</longitud>
      <latitud unidades="grados">40º 22' 48.29''</latitud>
      <altitud unidades="m">1963</altitud>
    </coordenadas>
  </llegada>

  <tipo valor="montaña"/>

  <referencias>
    <referencia>https://es.wikipedia.org/wiki/Vall_d%27Alba</referencia>
    <referencia>https://es.wikipedia.org/wiki/Aram%C3%B3n_Valdelinares</referencia>
    <referencia>https://www.lavuelta.es/es/etapa-7</referencia>
  </referencias>


  <fotografias>
    <fotografia archivo="../multimedia/Salida.jpg" descripcion="Lugar de Salida de la etapa"/>
  </fotografias>
  <videos>
    <video archivo="../multimedia/videoEtapa7.mp4" descripcion="Vídeo de la etapa"/>
  </videos>
  <sonidos>
    <sonido archivo="../multimedia/podcastEtapa7.mp3" descripcion="Podcast de la etapa"/>
  </sonidos>

  <hitos>
    <puerto categoria="segunda" bonificado="no">
      <nombre>Puerto El Remolcador</nombre>
      <coordenadas>
        <longitud unidades="grados">-0º 21' 00.72''</longitud>
        <latitud unidades="grados">40º 08' 27.96''</latitud>
        <altitud unidades="m">985</altitud>
      </coordenadas>
      <distancia unidades="km">52.2</distancia>
    </puerto>
    <puerto categoria="tercera" bonificado="no">
      <nombre>Alto de Zucaina</nombre>
      <coordenadas>
        <longitud unidades="grados">-0º 25' 15.60''</longitud>
        <latitud unidades="grados">40º 07' 53.40''</latitud>
        <altitud unidades="m">877</altitud>
      </coordenadas>
      <distancia unidades="km">66.5</distancia>
    </puerto>
    <puerto categoria="tercera" bonificado="no">
      <nombre>Puerto de Fuente de Rubielos</nombre>
      <coordenadas>
        <longitud unidades="grados">-0º 37' 10.20''</longitud>
        <latitud unidades="grados">40º 10' 22.80''</latitud>
        <altitud unidades="m">1003</altitud>
      </coordenadas>
      <distancia unidades="km">104.9</distancia>
    </puerto>
    <sprint_intermedio bonificado="si">
      <nombre>Sprint intermedio (Mora de Rubielos)</nombre>
      <coordenadas>
        <longitud unidades="grados">-0º 44' 52.80''</longitud>
        <latitud unidades="grados">40º 15' 41.40''</latitud>
        <altitud unidades="m">1052</altitud>
      </coordenadas>
      <distancia unidades="km">123.3</distancia>
    </sprint_intermedio>
    <puerto categoria="segunda" bonificado="no">
      <nombre>Puerto de San Rafael</nombre>
      <coordenadas>
        <longitud unidades="grados">-0º 42' 34.56''</longitud>
        <latitud unidades="grados">40º 20' 42.00''</latitud>
        <altitud unidades="m">1562</altitud>
      </coordenadas>
      <distancia unidades="km">136.3</distancia>
    </puerto>
  </hitos>

  <puntos_anonimos>
    <punto nombre="Vilafamés">
      <coordenadas>
        <longitud unidades="grados">-0º 03' 10.80''</longitud>
        <latitud unidades="grados">40º 07' 08.40''</latitud>
        <altitud unidades="m">260</altitud>
      </coordenadas>
      <distancia unidades="km">5.3</distancia>
    </punto>
    <punto nombre="La Barona">
      <coordenadas>
        <longitud unidades="grados">-0º 03' 49.57''</longitud>
        <latitud unidades="grados">40º 09' 59.29''</latitud>
        <altitud unidades="m">256</altitud>
      </coordenadas>
      <distancia unidades="km">10.8</distancia>
    </punto>
    <punto nombre="Les Useres">
      <coordenadas>
        <longitud unidades="grados">-0º 09' 46.19''</longitud>
        <latitud unidades="grados">40º 09' 26.06''</latitud>
        <altitud unidades="m">401</altitud>
      </coordenadas>
      <distancia unidades="km">20</distancia>
    </punto>
    <punto nombre="Mas d'Avall">
      <coordenadas>
        <longitud unidades="grados">-0º 10' 16.43''</longitud>
        <latitud unidades="grados">40º 07' 42.60''</latitud>
        <altitud unidades="m">410</altitud>
      </coordenadas>
      <distancia unidades="km">27.1</distancia>
    </punto>
    <punto nombre="Costur">
      <coordenadas>
        <longitud unidades="grados">-0º 10' 25.86''</longitud>
        <latitud unidades="grados">40º 07' 10.96''</latitud>
        <altitud unidades="m">472</altitud>
      </coordenadas>
      <distancia unidades="km">28.3</distancia>
    </punto>
    <punto nombre="Figueroles">
      <coordenadas>
        <longitud unidades="grados">-0º 14' 17.16''</longitud>
        <latitud unidades="grados">40º 07' 02.64''</latitud>
        <altitud unidades="m">437</altitud>
      </coordenadas>
      <distancia unidades="km">36.3</distancia>
    </punto>
    <punto nombre="Lucena del Cid">
      <coordenadas>
        <longitud unidades="grados">-0º 16' 59.99''</longitud>
        <latitud unidades="grados">40º 07' 59.99''</latitud>
        <altitud unidades="m">623</altitud>
      </coordenadas>
      <distancia unidades="km">42.3</distancia>
    </punto>
    <punto nombre="Castillo de Villamalefa">
      <coordenadas>
        <longitud unidades="grados">-0º 22' 49.40''</longitud>
        <latitud unidades="grados">40º 07' 49.80''</latitud>
        <altitud unidades="m">787</altitud>
      </coordenadas>
      <distancia unidades="km">55.9</distancia>
    </punto>
    <punto nombre="Zucaina">
      <coordenadas>
        <longitud unidades="grados">-0º 25' 08.18''</longitud>
        <latitud unidades="grados">40º 07' 55.16''</latitud>
        <altitud unidades="m">812</altitud>
      </coordenadas>
      <distancia unidades="km">66.3</distancia>
    </punto>
    <punto nombre="Montanejos">
      <coordenadas>
        <longitud unidades="grados">-0º 31' 22.44''</longitud>
        <latitud unidades="grados">40º 04' 05.52''</latitud>
        <altitud unidades="m">461</altitud>
      </coordenadas>
      <distancia unidades="km">83.4</distancia>
    </punto>
    <punto nombre="Puebla de Arenoso">
      <coordenadas>
        <longitud unidades="grados">-0º 35' 34.01''</longitud>
        <latitud unidades="grados">40º 06' 17.60''</latitud>
        <altitud unidades="m">740</altitud>
      </coordenadas>
      <distancia unidades="km">93.8</distancia>
    </punto>
    <punto nombre="Los Cantos">
      <coordenadas>
        <longitud unidades="grados">-0º 36' 32.58''</longitud>
        <latitud unidades="grados">40º 06' 58.93''</latitud>
        <altitud unidades="m">697</altitud>
      </coordenadas>
      <distancia unidades="km">96.2</distancia>
    </punto>
    <punto nombre="Olba">
      <coordenadas>
        <longitud unidades="grados">-0º 37' 00.01''</longitud>
        <latitud unidades="grados">40º 07' 59.99''</latitud>
        <altitud unidades="m">647</altitud>
      </coordenadas>
      <distancia unidades="km">100</distancia>
    </punto>
    <punto nombre="Fuentes de Rubielos">
      <coordenadas>
        <longitud unidades="grados">-0º 37' 07.68''</longitud>
        <latitud unidades="grados">40º 10' 09.12''</latitud>
        <altitud unidades="m">981</altitud>
      </coordenadas>
      <distancia unidades="km">104.4</distancia>
    </punto>
    <punto nombre="Rubielos de Mora">
      <coordenadas>
        <longitud unidades="grados">-0º 39' 11.05''</longitud>
        <latitud unidades="grados">40º 11' 20.18''</latitud>
        <altitud unidades="m">938</altitud>
      </coordenadas>
      <distancia unidades="km">109.9</distancia>
    </punto>
    <punto nombre="Mora de Rubielos">
      <coordenadas>
        <longitud unidades="grados">-0º 45' 12.24''</longitud>
        <latitud unidades="grados">40º 15' 05.76''</latitud>
        <altitud unidades="m">1064</altitud>
      </coordenadas>
      <distancia unidades="km">122</distancia>
    </punto>
    <punto nombre="Virgen de la Vega">
      <coordenadas>
        <longitud unidades="grados">-0º 42' 07.56''</longitud>
        <latitud unidades="grados">40º 21' 38.63''</latitud>
        <altitud unidades="m">1409</altitud>
      </coordenadas>
      <distancia unidades="km">138.5</distancia>
    </punto>
  </puntos_anonimos>

  <clasificacion_etapa>
    <clasificado posicion="1">
      <nombre>Andreas Leknessund</nombre>
      <equipo>UNO-X Mobility</equipo>
    </clasificado>
    <clasificado posicion="2">
      <nombre>Tobias Johannessen</nombre>
      <equipo>UNO-X Mobility</equipo>
      <diferencia>PT34S</diferencia>
    </clasificado>
    <clasificado posicion="3">
      <nombre>Wout Van Aert</nombre>
      <equipo>Team Visma</equipo>
      <diferencia>PT47S</diferencia>
    </clasificado>
  </clasificacion_etapa>

  <clasificacion_general>
    <clasificado posicion="1">
      <nombre>Tadej Pogacar</nombre>
      <equipo>Team UAE Team Emirates</equipo>
    </clasificado>
    <clasificado posicion="2">
      <nombre>Enric Mas</nombre>
      <equipo>Movistar Team</equipo>
      <diferencia>PT3M50S</diferencia>
    </clasificado>
    <clasificado posicion="3">
      <nombre>Primoz Roglic</nombre>
      <equipo>Red Bull Bora Hansgrohe</equipo>
      <diferencia>PT4M50S</diferencia>
    </clasificado>
  </clasificacion_general>

  <clasificacion_equipos>
    <equipo_clasificado posicion="1">
      <nombre>Decathlon CMA CGM Team</nombre>
    </equipo_clasificado>
    <equipo_clasificado posicion="2">
